# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'navigation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pylearn = QtWidgets.QLabel(self.centralwidget)
        self.pylearn.setGeometry(QtCore.QRect(270, 170, 47, 13))
        self.pylearn.setObjectName("pylearn")
        self.path_lbl = QtWidgets.QLabel(self.centralwidget)
        self.path_lbl.setGeometry(QtCore.QRect(220, 240, 47, 13))
        self.path_lbl.setObjectName("path_lbl")
        self.task_lbl = QtWidgets.QLabel(self.centralwidget)
        self.task_lbl.setGeometry(QtCore.QRect(220, 270, 47, 13))
        self.task_lbl.setObjectName("task_lbl")
        self.path = QtWidgets.QComboBox(self.centralwidget)
        self.path.setGeometry(QtCore.QRect(260, 240, 69, 22))
        self.path.setObjectName("path")
        self.path.addItem("")
        self.path.addItem("")
        self.path.addItem("")
        self.task = QtWidgets.QComboBox(self.centralwidget)
        self.task.setGeometry(QtCore.QRect(260, 270, 69, 22))
        self.task.setObjectName("task")
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setGeometry(QtCore.QRect(260, 320, 75, 23))
        self.start_btn.setObjectName("start_btn")
        self.select_lbl = QtWidgets.QLabel(self.centralwidget)
        self.select_lbl.setGeometry(QtCore.QRect(260, 200, 81, 20))
        self.select_lbl.setObjectName("select_lbl")
        self.profile = QtWidgets.QLabel(self.centralwidget)
        self.profile.setGeometry(QtCore.QRect(450, 30, 47, 13))
        self.profile.setObjectName("profile")
        self.rating = QtWidgets.QLabel(self.centralwidget)
        self.rating.setGeometry(QtCore.QRect(510, 30, 47, 13))
        self.rating.setObjectName("rating")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSignOut = QtWidgets.QAction(MainWindow)
        
        self.actionSignOut.setObjectName("actionSignOut")
        self.menuMenu.addAction(self.actionSignOut)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.actionSignOut.setText('Signout')
        
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuMenu.addAction(self.actionQuit)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pylearn.setText(_translate("MainWindow", "PYLEARN"))
        self.path_lbl.setText(_translate("MainWindow", "path"))
        self.task_lbl.setText(_translate("MainWindow", "task"))
        self.path.setItemText(0, _translate("MainWindow", "Path1"))
        self.path.setItemText(1, _translate("MainWindow", "Path2"))
        self.path.setItemText(2, _translate("MainWindow", "Path3"))
        self.start_btn.setText(_translate("MainWindow", "start"))
        self.select_lbl.setText(_translate("MainWindow", "Select Task"))
        self.profile.setText(_translate("MainWindow", "username"))
        self.rating.setText(_translate("MainWindow", "0.0 ★"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
